image:
  file: .devcontainer/.gitpod.Dockerfile
  context: .devcontainer

tasks:
  - init: >
      git submodule init
      && git submodule update
      && ./autogen.sh
      && ./configure --enable-ccache --enable-tracy --enable-tracy-capture --enable-tracy-gui
      && bear make
      && (cd lib/tracy/capture/build/unix ; make)
      && (cd lib/tracy/profiler/build/unix ; make)
      && make check
  - command: echo "Welcome to the stellar-core Gitpod development environment."

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd@0.1.5:VVxg4kW5VbJUP3ysCuG3Fg==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
